     /*-------------------------------------------------------------------------------------------*/
     /*                                                                                           */
     /* Copyright (c) 2014 Task Force IT-Consulting GmbH, Waltrop (Germany)                       */
     /* This software and the accompanying materials are made available                           */
     /* under the terms of the GNU General Public License version 2.0 (GPLv2)                     */
     /* which accompanies this distribution and is available at                                   */
     /* http://www.gnu.org/licenses/gpl-2.0.html                                                  */
     /*                                                                                           */
     /*-------------------------------------------------------------------------------------------*/
     /*                                                                                           */
     /* Rapid Fire                                                                                */
     /*-------------------------------------------------------------------------------------------*/
     /*  >>PRE-COMPILER<<                                                                         */
     /*    >>CRTCMD<< CRTCMD    CMD(&LI/&OB) +                                                    */
     /*                           SRCFILE(&SL/&SF) SRCMBR(&SM);                                   */
     /*    >>IMPORTANT<<                                                                          */
     /*      >>PARM<<  PGM(RF);                                                                   */
     /*      >>PARM<<  HLPID(*CMD);                                                               */
     /*      >>PARM<<  HLPPNLGRP(RF);                                                             */
     /*      >>PARM<<  PMTFILE(RF);                                                               */
     /*    >>END-IMPORTANT<<                                                                      */
     /*    >>EXECUTE<<                                                                            */
     /*  >>END-PRE-COMPILER<<                                                                     */
     /*                                                                                           */
     /*------------+--------+---------------------------------------------------------------------*/
     /*   Date     I Progr. I Description                                                         */
     /*------------+--------+---------------------------------------------------------------------*/
     /* 01.07.2014 I   FH   I Created                                                             */
     /*------------+--------+---------------------------------------------------------------------*/

             CMD        PROMPT(CON0001)
